### ISSUE TITLE
Error when running configure on Kali

### ISSUE THREAD

**Issue by zzzikai** [Nuand/kalibrate-bladeRF#10]
OS: Kali 2017.1

I have encountered the following error when trying to run configure:
`root@kali:~/kalibrate-bladeRF# ./configure 
checking for a BSD-compatible install... /usr/bin/install -c
...
checking for strtoul... yes
checking for strtol... yes
./configure: line 5095: syntax error near unexpected token `FFTW3,'
./configure: line 5095: `PKG_CHECK_MODULES(FFTW3, fftw3 >= 3.0)'
`

Have installed relevant BladeRF resources via **apt**:
`root@kali:~# apt list --installed | grep bladerf

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

bladerf/kali-rolling,now 0.2016.06-1+b2 amd64 [installed]
libbladerf-dev/kali-rolling,now 0.2016.06-1+b2 amd64 [installed]
libbladerf1/kali-rolling,now 0.2016.06-1+b2 amd64 [installed,automatic]
soapysdr0.5-2-module-bladerf/kali-rolling,now 0.3.2-2 amd64 [installed,automatic]`

I am wondering if there is something that I do to resolve the error. Is there something that I am missing?

**Comment by antoinet** [comment]
Solved this issue by installing `libfftw3-dev` and `pkg-config`:
```
$ apt install libfftw3-dev pkg-config
```
