### ISSUE TITLE
make error on kali linux

### ISSUE THREAD

**Issue by wooyunvip** [Nuand/kalibrate-bladeRF#13]
/kalibrate-bladeRF# make
make  all-recursive
make[1]: Entering directory '/root/kalibrate-bladeRF'
Making all in src
make[2]: Entering directory '/root/kalibrate-bladeRF/src'
g++ -DHAVE_CONFIG_H -I. -I..      -g -O2 -MT kal-arfcn_freq.o -MD -MP -MF .deps/kal-arfcn_freq.Tpo -c -o kal-arfcn_freq.o `test -f 'arfcn_freq.cc' || echo './'`arfcn_freq.cc
mv -f .deps/kal-arfcn_freq.Tpo .deps/kal-arfcn_freq.Po
g++ -DHAVE_CONFIG_H -I. -I..      -g -O2 -MT kal-c0_detect.o -MD -MP -MF .deps/kal-c0_detect.Tpo -c -o kal-c0_detect.o `test -f 'c0_detect.cc' || echo './'`c0_detect.cc
In file included from c0_detect.cc:32:0:
bladeRF_source.h:31:10: fatal error: libbladeRF.h: No such file or directory
 #include "libbladeRF.h"
          ^~~~~~~~~~~~~~
compilation terminated.
Makefile:442: recipe for target 'kal-c0_detect.o' failed
make[2]: *** [kal-c0_detect.o] Error 1
make[2]: Leaving directory '/root/kalibrate-bladeRF/src'
Makefile:376: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/root/kalibrate-bladeRF'
Makefile:317: recipe for target 'all' failed
make: *** [all] Error 2

What‘s  the problem  ?

**Comment by androth138** [comment]
It seems like you need to ensure you have libbladeRF.h in your library.

**Comment by Nuand** [comment]
Please see #18
