### ISSUE TITLE
Erro: compiling on Kali Linux

### ISSUE THREAD

**Issue by 0julio0** [Nuand/kalibrate-bladeRF#14]
hi, i`m trying install kalibrate-bladeRF on Kali Linux and received this error, 

root@kali:~/Code/kalibrate-bladeRF# make
make  all-recursive
make[1]: Entering directory '/root/Code/kalibrate-bladeRF'
Making all in src
make[2]: Entering directory '/root/Code/kalibrate-bladeRF/src'
g++ -DHAVE_CONFIG_H -I. -I..      -g -O2 -MT kal-bladeRF_source.o -MD -MP -MF .deps/kal-bladeRF_source.Tpo -c -o kal-bladeRF_source.o `test -f 'bladeRF_source.cc' || echo './'`bladeRF_source.cc
In file included from bladeRF_source.h:31:0,
                 from bladeRF_source.cc:39:
bladeRF_source.cc: In member function ‘int bladeRF_source::open(unsigned int)’:
bladeRF_source.cc:210:5: error: invalid conversion from ‘bladerf_channel {aka int}’ to ‘bladerf_channel_layout’ [-fpermissive]
     BLADERF_MODULE_RX,
     ^
/usr/local/include/libbladeRF.h:2419:15: note:   initializing argument 2 of ‘int bladerf_sync_config(bladerf*, bladerf_channel_layout, bladerf_format, unsigned int, unsigned int, unsigned int, unsigned int)’
 int CALL_CONV bladerf_sync_config(struct bladerf *dev,
               ^~~~~~~~~~~~~~~~~~~
make[2]: *** [Makefile:523: kal-bladeRF_source.o] Error 1
make[2]: Leaving directory '/root/Code/kalibrate-bladeRF/src'
make[1]: *** [Makefile:376: all-recursive] Error 1
make[1]: Leaving directory '/root/Code/kalibrate-bladeRF'
make: *** [Makefile:317: all] Error 2

Any one get same error?

**Comment by 0julio0** [comment]
This error just occour with BladeRF 2.0.
I made downgrade for libbladerf-dev and its work.
tks

**Comment by Nuand** [comment]
Please see #18
