### ISSUE TITLE
Make Error on ubuntu 18.04

### ISSUE THREAD

**Issue by merlinxcy** [Nuand/kalibrate-bladeRF#15]
```
g++ -DHAVE_CONFIG_H -I. -I..      -g -O2 -MT kal-bladeRF_source.o -MD -MP -MF .deps/kal-bladeRF_source.Tpo -c -o kal-bladeRF_source.o `test -f 'bladeRF_source.cc' || echo './'`bladeRF_source.cc
bladeRF_source.cc: In member function ‘int bladeRF_source::open(unsigned int)’:
bladeRF_source.cc:216:5: error: invalid conversion from ‘int’ to ‘bladerf_channel_layout’ [-fpermissive]
     );
     ^
In file included from bladeRF_source.h:31:0,
                 from bladeRF_source.cc:39:
```
What 's problem?
bladeRF_source.cc:216:5: error: invalid conversion from ‘int’ to ‘bladerf_channel_layout’ [-fpermissive]

**Comment by CorpOfHack** [comment]
Same problem... But before updating to last version ( I have had some warnings about outdated versions of libbladerf version) I have got the same problem... Before updating worked fine. Tested on Ubuntu 18.04 host and Kali Linux VM.
