### ISSUE TITLE
make error with libbladeRF 2.1.0

### ISSUE THREAD

**Issue by Meown12** [Nuand/kalibrate-bladeRF#17]
~/kalibrate-bladeRF$ make
make  all-recursive
make[1]: entering directory „/home/openbts/kalibrate-bladeRF“
Making all in src
make[2]: entering directory „/home/openbts/kalibrate-bladeRF/src“
g++ -DHAVE_CONFIG_H -I. -I..      -g -O2 -MT kal-bladeRF_source.o -MD -MP -MF .deps/kal-bladeRF_source.Tpo -c -o kal-bladeRF_source.o `test -f 'bladeRF_source.cc' || echo './'`bladeRF_source.cc
bladeRF_source.cc: In member function ‘int bladeRF_source::open(unsigned int)’:
bladeRF_source.cc:216:5: error: invalid conversion from ‘int’ to ‘bladerf_channel_layout’ [-fpermissive]
     );
     ^
In file included from bladeRF_source.h:31:0,
                 from bladeRF_source.cc:39:
/usr/local/include/libbladeRF.h:2540:15: note:   initializing argument 2 of ‘int bladerf_sync_config(bladerf*, bladerf_channel_layout, bladerf_format, unsigned int, unsigned int, unsigned int, unsigned int)’
 int CALL_CONV bladerf_sync_config(struct bladerf *dev,
               ^
Makefile:512: goal „kal-bladeRF_source.o“ failed
make[2]: *** [kal-bladeRF_source.o] errors 1
make[2]: leaving directory „/home/openbts/kalibrate-bladeRF/src“ 
Makefile:376: goal „all-recursive“ failed
make[1]: *** [all-recursive] errors 1
make[1]: leaving directory „/home/openbts/kalibrate-bladeRF“
Makefile:317: goal „all“ failed
make: *** [all] errors 2

I am using libbladeRF 2.1.
Any suggestions would be appreciated.

**Comment by androth138** [comment]
I'm having an issue with the bladeRF_source.cc too.  Have you had any luck solving? I'm going to dig around in the code.  Pretty green on coding :/

bladeRF_source.cc: In member function ‘int bladeRF_source::save_dac(int)’:
bladeRF_source.cc:139:48: error: cannot convert ‘bladerf_fpga_size’ to ‘bladerf*’ for argument ‘1’ to ‘bladerf_image* bladerf_alloc_cal_image(bladerf*, bladerf_fpga_size, uint16_t)’
  image = bladerf_alloc_cal_image(fpga_size, dac);
                                                ^
bladeRF_source.cc:144:33: error: ‘BLADERF_FLASH_EB_CAL’ was not declared in this scope
  rv = bladerf_erase_flash(bdev, BLADERF_FLASH_EB_CAL,
                                 ^
bladeRF_source.cc:145:4: error: ‘BLADERF_FLASH_EB_LEN_CAL’ was not declared in this scope
    BLADERF_FLASH_EB_LEN_CAL);
    ^
bladeRF_source.cc:150:46: error: ‘BLADERF_FLASH_TO_PAGES’ was not declared in this scope
  page = BLADERF_FLASH_TO_PAGES(image->address);
                                              ^
bladeRF_source.cc: In member function ‘int bladeRF_source::open(unsigned int)’:
bladeRF_source.cc:216:5: error: invalid conversion from ‘int’ to ‘bladerf_channel_layout’ [-fpermissive]
     );
     ^
In file included from bladeRF_source.h:31:0,
                 from bladeRF_source.cc:39:
/usr/local/include/libbladeRF.h:2553:15: note:   initializing argument 2 of ‘int bladerf_sync_config(bladerf*, bladerf_channel_layout, bladerf_format, unsigned int, unsigned int, unsigned int, unsigned int)’
 int CALL_CONV bladerf_sync_config(struct bladerf *dev,

Ubuntu16
bladeRF-cli version:        1.7.1-git-718c487
libbladeRF version:         2.2.0-git-718c487
Firmware version:           2.3.2
FPGA version:               0.6.0 (configured by USB host)

**Comment by Meown12** [comment]
Hi Andrew,
I actually think I managed to fix my issue - in the Release Notes 2.0 of the libbladeRF it was mentioned that BLADERF_MODULE_RX (and *_TX) had been changed to an enum: bladerf_channel_layout. The release notes mention that you should replace BLADERF_MODULE_RX with BLADERF_CHANNEL_RX(0) as this is seemingly a macro for it. However, this still gives you an int and so I casted that into bladerf_channel_layout.  Fixed line:
`static_cast<bladerf_channel_layout>(BLADERF_CHANNEL_RX(0))` (line 210 in bladeRF_source.cc / 2nd argument of bladerf_sync_config in the open(subdev) function).
This allows compilation - And the program seems to work as intended (I believe - I never used it before, so I don't know what to expect in terms of performance).
Regarding your issue I am currently unable to reproduce it, mainly because I realized, that my libbladeRF version is from last December (commit 5ff598a from the 3rd of December 2018 to be exact) and I noticed that around mid December the libbladeRF structure regarding the constants causing trouble was changed.
I will get my current work with the calibration done first and then I will update and check again.

Maybe you are able to fix it yourself in the meantime, let me know whether my solution removes at least the last of your errors.

All the best 

Max
[bladeRF_source.cc.zip](https://github.com/Nuand/kalibrate-bladeRF/files/3057966/bladeRF_source.cc.zip)

**Comment by Meown12** [comment]
Hi again,
checkout the fork + pull request I created, as they should solve your problem.
Best Regards,

Max

**Comment by androth138** [comment]
Max,

Thanks a lot. I'll dig into it this weekend and let you know how it goes.
Glad you're up and running!

Andrew

**Comment by Meown12** [comment]
Hi,
first I am sorry for closing this issue prematurely. For everyone wondering - the solution proposed by me before seems to still have some issues on Andrew's machine - thats why I reopened this. (error described in: #18 ) 
I am surprised by your error @androth138 , because both functions are used in the include files and bladerf_erase_flash and bladerf_write_flash are seen as deprecated from what I see, thats why I used the bytes function (also because only for them address constants are available, I believe. Could you verify, (simply `grep` them) that they are in both your include/libbladeRF.h and your src/bladerf.c, please?.
For it not finding anything - do you mean it doesnt find any GSM bands to lock on? Try different bands, see the -h, I for example couldnt find anything on GSM850 but GSM900 worked just fine. This part of the code should be completely detached from the first part so your work around should work just fine until you try to save it to the flash I assume. Don't know what will happen then.
Try a few different bands, preferably with a GSM-antenna (you may need a 900MHz and an 1800MHz antenna for all the band options - see wikipedia https://en.wikipedia.org/wiki/GSM_frequency_bands) but a 1.5 GHz antenna worked for me too  .

Hope this helps you to start off too,

Max

**Comment by androth138** [comment]
Max(@Meown12),

No worries and thanks for the continued help.  I rebooted and running now with no issues.  Should have ran the restart before responding (#1 solution for most issues lol).  To answer your question, in my include/libbladeRF.h and src/bladerf.c I have both functions mentioned as well as the ones ending in _bytes. 

I've have a decent background in Cellular and RF Theory so if you have any issues with that perhaps I can return the favor.

Andrew
