### ISSUE TITLE
kalibrating issue while make command 

### ISSUE THREAD

**Issue by crawsec** [Nuand/kalibrate-bladeRF#19]
while make command kalibrate throws an error.

sigintos@sigintos:~/Desktop/kalibrate-bladeRF$ make -j10
make  all-recursive
make[1]: Entering directory '/home/sigintos/Desktop/kalibrate-bladeRF'
Making all in src
make[2]: Entering directory '/home/sigintos/Desktop/kalibrate-bladeRF/src'
g++ -DHAVE_CONFIG_H -I. -I..      -g -O2 -MT kal-bladeRF_source.o -MD -MP -MF .deps/kal-bladeRF_source.Tpo -c -o kal-bladeRF_source.o `test -f 'bladeRF_source.cc' || echo './'`bladeRF_source.cc
bladeRF_source.cc: In member function ‘int bladeRF_source::save_dac(int)’:
bladeRF_source.cc:139:48: error: cannot convert ‘bladerf_fpga_size’ to ‘bladerf*’ for argument ‘1’ to ‘bladerf_image* bladerf_alloc_cal_image(bladerf*, bladerf_fpga_size, uint16_t)’
  image = bladerf_alloc_cal_image(fpga_size, dac);
                                                ^
bladeRF_source.cc:144:33: error: ‘BLADERF_FLASH_EB_CAL’ was not declared in this scope
  rv = bladerf_erase_flash(bdev, BLADERF_FLASH_EB_CAL,
                                 ^
bladeRF_source.cc:145:4: error: ‘BLADERF_FLASH_EB_LEN_CAL’ was not declared in this scope
    BLADERF_FLASH_EB_LEN_CAL);
    ^
bladeRF_source.cc:150:46: error: ‘BLADERF_FLASH_TO_PAGES’ was not declared in this scope
  page = BLADERF_FLASH_TO_PAGES(image->address);
                                              ^
bladeRF_source.cc: In member function ‘int bladeRF_source::open(unsigned int)’:
bladeRF_source.cc:216:5: error: invalid conversion from ‘int’ to ‘bladerf_channel_layout’ [-fpermissive]
     );
     ^
In file included from bladeRF_source.h:31:0,
                 from bladeRF_source.cc:39:
/usr/local/include/libbladeRF.h:2553:15: note:   initializing argument 2 of ‘int bladerf_sync_config(bladerf*, bladerf_channel_layout, bladerf_format, unsigned int, unsigned int, unsigned int, unsigned int)’
 int CALL_CONV bladerf_sync_config(struct bladerf *dev,
               ^
Makefile:512: recipe for target 'kal-bladeRF_source.o' failed
make[2]: *** [kal-bladeRF_source.o] Error 1
make[2]: Leaving directory '/home/sigintos/Desktop/kalibrate-bladeRF/src'
Makefile:376: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/sigintos/Desktop/kalibrate-bladeRF'
Makefile:317: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Nuand** [comment]
Please see #18
